services:

    mysql:
      container_name: betterstrava-mysql
      image: mysql:8.0.35
      ports:
        - 3306:3306
      environment:
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      volumes:
        - mysql:/var/lib/mysql
        - "./initialisation-DB.sql:/docker-entrypoint-initdb.d/init.sql"

    mongodb:
      container_name: betterstrava-mongodb
      image: mongo:6.0.3
      ports:
        - 27010:27017
      environment:
        - MONGO_INITDB_ROOT_USERNAME=root
        - MONGO_INITDB_ROOT_PASSWORD=root
        - ME_CONFIG_MONGODB_URL=mongodb://root:root@mongo:27010/
      volumes:
        - mongodb:/data/db
        - "./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js"

    bs-api:
      container_name: betterstrava-api
      image: ghcr.io/bs-iutrdz/s5-betterstravaapi:main
      ports:
        - 8081:8080

volumes:
  mysql:
  mongodb: