services:

  mysql:
    container_name: betterstrava-mysql
    image: mysql:8.0.35
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql:/var/lib/mysql
      - "./initialisation-DB.sql:/docker-entrypoint-initdb.d/init.sql"
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=${MYSQL_ROOT_PASSWORD}
      timeout: 10s
      retries: 10

  mongodb:
    container_name: betterstrava-mongodb
    image: mongo:6.0.3
    ports:
      - 27010:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - ME_CONFIG_MONGODB_URL=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017/
    volumes:
      - mongodb:/data/db
      - "./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js"
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      timeout: 10s
      retries: 10

  bs-api:
    container_name: betterstrava-api
    image: ghcr.io/bs-iutrdz/s5-betterstravaapi:main
    ports:
      - 8081:8080
    depends_on:
      mongodb:
        condition: service_healthy
      mysql:
        condition: service_healthy
    environment:
      - spring.data.mongodb.uri=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongodb:27017/betterstrava?authSource=admin
      - spring.datasource.url=jdbc:mysql://mysql/betterStrava
      - spring.datasource.username=${MYSQL_DATASOURCE_USERNAME}
      - spring.datasource.password=${MYSQL_DATASOURCE_PASSWORD}
      - debug=false
    volumes:
      - ".env:/.env"

volumes:
  mysql:
  mongodb: